version: '3'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc123456
      - POSTGRES_DB=devDb
    networks:
      - nestjs-network
networks:
  nestjs-network:
