version: '3'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc123456
      - POSTGRES_DB=devDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nestjs-network
  prisma:
    image: prismagraphql/prisma:latest
    container_name: prisma
    ports:
      - 4466:4466
    environment:
      - PRISMA_DATABASE_URL=postgresql://postgres:Abc123456@dev-database:5432/devDb
    volumes:
      - prisma-data:/prisma
    networks:
      - nestjs-network
  nestjs-server:
    image: nestjs
    container_name: nestjs-server
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_HOST=dev-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc123456
      - POSTGRES_DB=devDb
    networks:
      - nestjs-network

networks:
  nestjs-network:

volumes:
  postgres-data:
  prisma-data:
